# Approximation of the cost of the centralized and decentralized systems for a finite N in the SIR model with vaccinations

In [5]:
import matplotlib.pyplot as plt
import numpy as np
import math
import scipy.io as sio

from mpl_toolkits.mplot3d import Axes3D
#import matplotlib.pyplot as plt
from matplotlib import cm
from matplotlib.ticker import LinearLocator, FormatStrFormatter
#import numpy

In [13]:
# system parameters
gamma = 73.0      # infection rate
rho = 36.5        # recovery rate
vac_min = 0.0     # minimum vaccination rate
theta = 10.0      # maximum vaccination rate
T = 1             # time horizon

# costs
c_V = 0.5         # cost per unit time of vaccination
c_I = 36.5        # cost per unit time of infection

# uniformization constant
C=int(1000)
TimeHorizon = int(T*C)

N=10
mfe_cost = []; mfopt_cost = []
for s0 in range(1,N):
    mfe_cost_v = []; mfopt_cost_v = []
    for i0 in range(1,N):
        if N-s0-i0>0: 
            I0=i0/N; S0=s0/N
            print(I0,S0)
            val_mfe_cost = equilibrium_n_players()
            #val_mfopt_cost = global_optimum()
        else:
            val_mfe_cost = 0
            #val_mfopt_cost = -1
        mfe_cost_v.append(val_mfe_cost)
        #mfopt_cost_v.append(val_mfopt_cost)
    mfe_cost.append(mfe_cost_v)#; mfopt_cost.append(mfopt_cost_v)
    
mat_mfe_cost=np.array([np.array(xi) for xi in mfe_cost])
#mat_mfopt_cost=np.array([np.array(xi) for xi in mfopt_cost])
sio.savemat('data/Nfinite_eq_cost_N10.mat', {'mfe_cost':mfe_cost})
#sio.savemat('data/Nfinite_opt_cost_N10.mat', {'mfopt_cost':mfopt_cost})

0.1 0.1
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_p

BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m

BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
Equilibrium found. Equilibrium policy at t=0:
[[ 0.  0.  0.  0. 10. 10. 10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0. 10. 10. 10. 10. 10. 10.  0.]
 [ 0.  0.  0.  0. 10. 10. 10. 10. 10.  0.  0.]
 [ 0.  0.  0. 10. 10. 10. 10. 10.

BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
Equilibrium found. Equilibrium policy at t=0:
[[ 0.  0.  0.  0. 10. 10. 10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0. 10. 10. 10. 10. 10. 10.  0.]
 [ 0.  0.  0.  0. 10. 10. 10. 10. 10.  0.  0.]
 [ 0.  0.  0. 10. 10. 10. 10. 10.  0.  0.  0.]
 [ 0.  0.  0. 10. 10. 10. 10.  0.  0.  0.  0.]
 [ 0.  0.  0. 10. 10. 10.  0.  0.  0.  0.  0.]
 [ 0.  0. 10. 10. 10.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10. 10.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0

BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
Equilibrium found. Equilibrium policy at t=0:
[[ 0.  0.  0.  0. 10. 10. 10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0. 10. 10. 10. 10. 10. 10.  0.]
 [ 0.  0.  0.  0. 10. 10. 10. 10. 10.  0.  0.]
 [ 0.  0.  0. 10. 10. 10. 10. 10.  0.  0.  0.]
 [ 0.  0.  0. 10. 10. 10. 10.  0.  0.  0.  0.]
 [ 0.  0.  0. 10. 10. 10.  0.  0.  0.  0.  0.]
 [ 0.  0. 10. 10. 10.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10. 10.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]
0.3 0.3
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m

BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m

BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m

BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
Equilibrium found. Equilibrium policy at t=0:
[[ 0.  0.  0.  0. 10. 10. 10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0. 10. 10. 10. 10. 10. 10.  0.]
 [ 0.  0.  0.  0. 10. 10. 10. 10. 10.  0.  0.]
 [ 0.  0.  0. 10. 10. 10. 10. 10.

BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
BR_pol and m_pol do not coindice. Updating m_pol...
Equilibrium found. Equilibrium policy at t=0:
[[ 0.  0.  0.  0. 10. 10. 10. 10. 10. 10. 10.]
 [ 0.  0.  0.  0. 10. 10. 10. 10. 10. 10.  0.]
 [ 0.  0.  0.  0. 10. 10. 10. 10. 10.  0.  0.]
 [ 0.  0.  0. 10. 10. 10. 10. 10.  0.  0.  0.]
 [ 0.  0.  0. 10. 10. 10. 10.  0.  0.  0.  0.]
 [ 0.  0.  0. 10. 10. 10.  0.  0.  0.  0.  0.]
 [ 0.  0. 10. 10. 10.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10. 10.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0

The function to compute the N-player equilibrium

In [14]:
def trans_prob(m_s, m_i, m_pi, pl0_pi, N, C):
    p_x = np.zeros(3)
    p_m = np.zeros(3)
    # transition probabilities of Player 0
    p_x[0] = 1. * gamma / C * m_i / N
    p_x[1] = 1. * rho / C
    p_x[2] = 1. * pl0_pi / C
    # transition probabilities of the mass
    p_m[0] = 1. * gamma * N / C * m_s / N * m_i / N
    p_m[1] = 1. * m_i / N * rho * N / C
    p_m[2] = 1. * m_s / N * m_pi * N / C

    return p_x, p_m


def best_response_n_players(m_pol):

    if C < N * max(theta, gamma, rho): raise Exception('Higher value of C required')

    # checking that S0*N and I0*N are integers
    if not (1. * S0 * N).is_integer():
        raise Exception('S0*N is not integer')

    if not (1. * I0 * N).is_integer():
        raise Exception('I0*N is not integer')

    # Pl0 cost at susceptible and infected state: Js and Ji
    Js = np.zeros((C + 1, N + 1, N + 1))
    Ji = np.zeros((C + 1, N + 1, N + 1))
    # Best response of Player 0
    BR_pol = np.zeros((C + 1, N + 1, N + 1))

    for t in range(C, 0, -1):
        for ms in range(0, N + 1):
            for mi in range(0, N - ms + 1):
                if c_V - Js[t, ms, mi] < 0:
                    BR_pol[t - 1, ms, mi] = theta
                else:
                    BR_pol[t - 1, ms, mi] = 0
                px, pm = trans_prob(ms, mi, m_pol[t - 1, ms, mi], BR_pol[t - 1, ms, mi], N, C)
                Js[t - 1, ms, mi] = (
                    c_V * BR_pol[t - 1, ms, mi] / C +                               # pl0 instantaneous cost at susceptible state
                    (px[0] * Ji[t, ms, mi] if mi > 0 else 0) +                      # pl0 infection
                    (px[2] * 0) +                                                   # pl0 vaccination: the cost when it is recovered is 0
                    (pm[0] * Js[t, ms - 1, mi + 1] if ms > 0 else 0) +              # infection of mass
                    (pm[1] * Js[t, ms, mi - 1] if mi > 0 else 0) +                  # recovery of mass
                    (pm[2] * Js[t, ms - 1, mi] if ms > 0 else 0) +                  # vaccination of mass
                    (1 - px[0] - px[2] - pm[0] - pm[1] - pm[2]) * Js[t, ms, mi])    # no transition
                Ji[t - 1, ms, mi] = (
                    c_I / C +                                               # pl0 instantaneous cost at infected state
                    (px[1] * 0) +                                           # pl0 recovery: the cost when it is recovered is 0
                    (pm[0] * Ji[t, ms - 1, mi + 1] if ms > 0 else 0) +      # infection of mass
                    (pm[1] * Ji[t, ms, mi - 1] if mi > 0 else 0) +          # recovery of mass
                    (pm[2] * Ji[t, ms - 1, mi] if ms > 0 else 0) +          # vaccination of mass
                    (1 - px[1] - pm[0] - pm[1] - pm[2]) * Ji[t, ms, mi])    # no transition
    return BR_pol, Js, Ji


def equilibrium_n_players():
    # the policy of the mass is never vaccinate
    m_pol = np.zeros((C + 1, N + 1, N + 1))
    # the policy of the mass is to always vaccinate with max rate
    # m_pol=theta*np.ones((C+1,N+1,N+1));

    BR_pol, Js, Ji = best_response_n_players(m_pol)
    # print(BR_pol[0])

    while 0 < 1:
        if np.allclose(BR_pol, m_pol):
            print("Equilibrium found. Equilibrium policy at t=0:")
            #print(BR_pol[0])
            break
        else:
            print("BR_pol and m_pol do not coindice. Updating m_pol...")
            #print("The optimal cost in S state when S0 and I0 are 0.4:")
            #print(Js[0, int(S0 * N), int(I0 * N)])
            #print(np.nonzero(BR_pol-m_pol))
            # print(BR_pol[0])
            m_pol = BR_pol
            BR_pol, Js, Ji = best_response_n_players(m_pol)

    cost_eq=Js[0]*S0+Ji[0]*I0
    return cost_eq

The function to compute the global optimum

In [2]:
def global_optimum():
    """
    This method uses a divide and conquer approach to compute the minimum value. 
    It assumes that the optimal policy is a bang-bang policy with a unique jump time"""
    my_policy=np.zeros(TimeHorizon+1);
    j=0;
    v=np.zeros(TimeHorizon+1);
    x_S=np.zeros(TimeHorizon+1);
    x_I=np.zeros(TimeHorizon+1);
    
    def compute_cost(t_critical):
        x_S[0]=S0; x_I[0]=I0;
        if v[t_critical] > 0: return
        for i in range(TimeHorizon):
            my_policy[i] = theta if i<t_critical else vac_min
            x_S[i+1] = x_S[i]+(-gamma*x_I[i]*x_S[i] - my_policy[i]*x_S[i])/C;
            x_I[i+1] = x_I[i]+(gamma*x_I[i]*x_S[i] - rho*x_I[i])/C;    

        v[t_critical] = sum(1.*c_I*x_I/C+1.*c_V*x_S*my_policy/C);    
    
    t_critical = int(C/2)
    deltaT = int(C/4)
    for i in range(20):
        for t in [t_critical,t_critical+1]:
            compute_cost(t)
        if v[t_critical+1]>v[t_critical]: 
            t_critical -= deltaT
        else: 
            t_critical += deltaT
        deltaT = min(t_critical,int(np.ceil(deltaT/2)))
        
    cost_opt=v[t_critical]
    mypos=t_critical
    return cost_opt; 